### ISSUE TITLE
Notes Page Document Filter is not Working

### ISSUE THREAD

**Issue by xPugnocode** [edwinSp1/js-express-canvas-school-app#11]
Error: Notes page document filter isn't working as expected.
-
Expected Outcome: Returns notes page with filtered results.
Actual Outcome: When clicking `Apply Filters` the refreshed page does not filter the results and the filter select boxes are back to being all checked and no filtered results were given.

**Comment by edwinSp1** [comment]
ay. fuck. i shoulda seen this coming when I was implementing pagination

**Comment by xPugnocode** [comment]
What would a possible fix look like?

**Comment by edwinSp1** [comment]
Fixed, check latest patch
