### ISSUE TITLE
sleep page still crashing for older accounts

### ISSUE THREAD

**Issue by xPugnocode** [edwinSp1/js-express-canvas-school-app#4]
This is using the Brian Wei account
![image](https://github.com/edwinSp1/js-express-canvas-school-app/assets/111609120/2db0cabe-9925-40cc-b8d3-c216b542e2bf)

**Comment by edwinSp1** [comment]
=> (node:3879173) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'schedule' of null

On it.

**Comment by edwinSp1** [comment]
issue identified: account created before this line of code was added: 
db.insert('users', 'userdata', {username:username})

2. 
The production server runs on nodeJS 14.20, which does not support the nullish coalsescing operator.

**Comment by edwinSp1** [comment]
issue fixed. Shipping to production.
